<div class="row">
    <div class="col-md-12 col-lg-12 col-xs-12">
        <form class="form-horizontal" method="post" action="/admin/sections/update/<?php echo intval($id); ?>">
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Наименование раздела:</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="name" name="name" value="<?php echo $section->getName(); ?>">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-9">
                    <button type="submit" class="btn btn-default">Сохранить</button>
                </div>
            </div>
        </form>
    </div>
</div>